/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarInformationList;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harrsini Sekar
 */
public class ViewAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAdminJPanel
     */
    private JPanel UserProcessContainer;
    private CarInformationList carInformationList;
    private Car car;
    ViewAdminJPanel(JPanel UserProcessContainer, CarInformationList carInformationList) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.carInformationList = carInformationList;
        this.car = car;
        populateTable();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        citytab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnFirstCarSearch = new javax.swing.JButton();
        btnSearchAvail = new javax.swing.JButton();
        countrowTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        countRowNATextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        MinComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        MaxComboBox = new javax.swing.JComboBox<>();
        btnSearchSeats = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ModelNumberTextField = new javax.swing.JTextField();
        btnSearchModelNumber = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        SerialNumberTextField = new javax.swing.JTextField();
        btnSearchSerialNumber = new javax.swing.JButton();
        citypanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        CityTextField = new javax.swing.JTextField();
        btnSearchCity = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnMCSearch = new javax.swing.JButton();
        MCComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        txtFleetTime = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ManuYearTextField = new javax.swing.JTextField();
        btnManuYearSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnSearchBrand = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BrandTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(1500, 1500));

        citytab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnFirstCarSearch.setText("Search the first available car");
        btnFirstCarSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstCarSearchActionPerformed(evt);
            }
        });

        btnSearchAvail.setText("List the Available cars");
        btnSearchAvail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAvailActionPerformed(evt);
            }
        });

        jButton2.setText("List the Unavailable Cars");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnSearchAvail)
                        .addGap(18, 18, 18)
                        .addComponent(countrowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(countRowNATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(btnFirstCarSearch)))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchAvail)
                    .addComponent(countrowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(countRowNATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnFirstCarSearch)
                .addGap(33, 33, 33))
        );

        citytab.addTab("Availability", jPanel1);

        jLabel2.setText("Min Seats");

        MinComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        MinComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Max Seats");

        MaxComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        btnSearchSeats.setText("SEARCH");
        btnSearchSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSeatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(MinComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(MaxComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(btnSearchSeats)))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(MinComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(MaxComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnSearchSeats)
                .addContainerGap())
        );

        citytab.addTab("Capacity", jPanel4);

        jLabel4.setText("Enter the Model number you wish to search");

        btnSearchModelNumber.setText("SEARCH");
        btnSearchModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchModelNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(ModelNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(btnSearchModelNumber)))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ModelNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnSearchModelNumber)
                .addContainerGap())
        );

        citytab.addTab("Model Number", jPanel5);

        jLabel5.setText("Enter the Serial number you wish to search");

        btnSearchSerialNumber.setText("SEARCH");
        btnSearchSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSerialNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(SerialNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(btnSearchSerialNumber)))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SerialNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnSearchSerialNumber)
                .addContainerGap())
        );

        citytab.addTab("Serial Number", jPanel6);

        jLabel6.setText("Enter the city of the car you wish to search");

        btnSearchCity.setText("SEARCH");
        btnSearchCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout citypanelLayout = new javax.swing.GroupLayout(citypanel);
        citypanel.setLayout(citypanelLayout);
        citypanelLayout.setHorizontalGroup(
            citypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(citypanelLayout.createSequentialGroup()
                .addGroup(citypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(citypanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel6)
                        .addGap(27, 27, 27)
                        .addComponent(CityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(citypanelLayout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(btnSearchCity)))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        citypanelLayout.setVerticalGroup(
            citypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(citypanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(citypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnSearchCity)
                .addContainerGap())
        );

        citytab.addTab("City", citypanel);

        btnMCSearch.setText("SEARCH");
        btnMCSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMCSearchActionPerformed(evt);
            }
        });

        MCComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Expired", "Active" }));
        MCComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCComboBoxActionPerformed(evt);
            }
        });

        jLabel9.setText("Maintanence Certificate");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(85, 85, 85)
                .addComponent(MCComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(321, 321, 321))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(btnMCSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MCComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(29, 29, 29)
                .addComponent(btnMCSearch)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        citytab.addTab("Maintanence Certificate", jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton4.setText("Find the last updated time");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jButton4)
                .addGap(98, 98, 98)
                .addComponent(txtFleetTime, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(388, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(txtFleetTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        citytab.addTab("Fleet time Update", jPanel9);

        jLabel7.setText("Search by Manufactured Year : ");

        btnManuYearSearch.setText("SEARCH");
        btnManuYearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManuYearSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel7)
                        .addGap(30, 30, 30)
                        .addComponent(ManuYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(btnManuYearSearch)))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ManuYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnManuYearSearch)
                .addGap(30, 30, 30))
        );

        citytab.addTab("Manufactured Year", jPanel3);

        jLabel8.setText("Search by Brand : ");

        btnSearchBrand.setText("SEARCH");
        btnSearchBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBrandActionPerformed(evt);
            }
        });

        jButton1.setText("List all car brands used by Uber");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BrandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchBrand))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jButton1)))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btnSearchBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
        );

        citytab.addTab("Brand", jPanel2);

        viewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand", "Model No", "Min Seats", "Max seats", "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel1.setText("Criteria Search");

        btnBack1.setText("<< Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 927, Short.MAX_VALUE)
                .addComponent(btnViewDetails)
                .addGap(24, 24, 24))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btnBack1)
                            .addGap(225, 225, 225)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(citytab, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(553, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnViewDetails))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(61, 61, 61)
                    .addComponent(citytab, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(41, 41, 41)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 33, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFirstCarSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstCarSearchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)viewTable.getModel();
        dtm.setRowCount(0);

        for ( Car car : carInformationList.getCarInformationList())
        {
            if (car.isAvailable()==true){
                Object row[] = new Object[5];
                row[0] = car;
                row[1] = car.getModel_num();
                row[2] = car.getMin_seats();
                row[3] = car.getMax_seats();
                row[4] = car.getAvailble_city();
                dtm.addRow(row);
                break;
            }
        }
    }//GEN-LAST:event_btnFirstCarSearchActionPerformed

    private void btnSearchAvailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAvailActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)viewTable.getModel();
        dtm.setRowCount(0);
        int count = 0;
        for ( Car car : carInformationList.getCarInformationList())
        {
            if(car.isAvailable() == true){
                Object row[] = new Object[5];
                row[0] = car;
                row[1] = car.getModel_num();
                row[2] = car.getMin_seats();
                row[3] = car.getMax_seats();
                row[4] = car.getAvailble_city();
                dtm.addRow(row);
                count++;
            }
            countrowTextField.setText(String.valueOf(count));
        }
    }//GEN-LAST:event_btnSearchAvailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)viewTable.getModel();
        dtm.setRowCount(0);
        int count = 0;
        for ( Car car : carInformationList.getCarInformationList())
        {
            if(car.isAvailable() == false){
                Object row[] = new Object[5];
                row[0] = car;
                row[1] = car.getModel_num();
                row[2] = car.getMin_seats();
                row[3] = car.getMax_seats();
                row[4] = car.getAvailble_city();
                dtm.addRow(row);

                count++;
            }
            countRowNATextField.setText(String.valueOf(count));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void MinComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinComboBoxActionPerformed

    private void btnSearchSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSeatsActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)viewTable.getModel();
        dtm.setRowCount(0);

        int minseat = Integer.parseInt(String.valueOf(MinComboBox.getSelectedItem()));
        int maxseat = Integer.parseInt(String.valueOf(MaxComboBox.getSelectedItem()));

        for ( Car car : carInformationList.getCarInformationList())
        {
            if(car.getMin_seats() >= minseat && car.getMax_seats() <= maxseat)
            {
                Object row[] = new Object[5];
                row[0] = car;
                row[1] = car.getModel_num();
                row[2] = car.getMin_seats();
                row[3] = car.getMax_seats();
                row[4] = car.getAvailble_city();
                dtm.addRow(row);
            }
        }

    }//GEN-LAST:event_btnSearchSeatsActionPerformed

    private void btnSearchModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchModelNumberActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)viewTable.getModel();
        dtm.setRowCount(0);
        String Modelnum = ModelNumberTextField.getText();
        for ( Car car : carInformationList.getCarInformationList())
        {
            if(car.getModel_num().equals(Modelnum)){
                Object row[] = new Object[5];
                row[0] = car;
                row[1] = car.getModel_num();
                row[2] = car.getMin_seats();
                row[3] = car.getMax_seats();
                row[4] = car.getAvailble_city();
                dtm.addRow(row);
            }
        }
    }//GEN-LAST:event_btnSearchModelNumberActionPerformed

    private void btnSearchSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSerialNumberActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)viewTable.getModel();
        dtm.setRowCount(0);
        int Serialnum = Integer.parseInt(SerialNumberTextField.getText());
        for ( Car car : carInformationList.getCarInformationList())
        {
            if(car.getSerial_num() == Serialnum){
                Object row[] = new Object[5];
                row[0] = car;
                row[1] = car.getModel_num();
                row[2] = car.getMin_seats();
                row[3] = car.getMax_seats();
                row[4] = car.getAvailble_city();
                dtm.addRow(row);

            }
        }
    }//GEN-LAST:event_btnSearchSerialNumberActionPerformed

    private void btnSearchCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCityActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)viewTable.getModel();
        dtm.setRowCount(0);
        String city = CityTextField.getText();
        for ( Car car : carInformationList.getCarInformationList())
        {
            if(car.getAvailble_city().equals(city)){
                Object row[] = new Object[5];
                row[0] = car;
                row[1] = car.getModel_num();
                row[2] = car.getMin_seats();
                row[3] = car.getMax_seats();
                row[4] = car.getAvailble_city();
                dtm.addRow(row);
            }
        }

    }//GEN-LAST:event_btnSearchCityActionPerformed

    private void btnMCSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMCSearchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)viewTable.getModel();
        dtm.setRowCount(0);
        int MCSearch = Integer.parseInt(String.valueOf(MCComboBox.getSelectedIndex()));
        for ( Car car : carInformationList.getCarInformationList()){
            if(MCSearch == 0) {
                if(car.isMaintenance_certificate() == true )
                {
                    Object row[] = new Object[5];
                    row[0] = car;
                    row[1] = car.getModel_num();
                    row[2] = car.getMin_seats();
                    row[3] = car.getMax_seats();
                    row[4] = car.getAvailble_city();
                    dtm.addRow(row);
                }
            }
            if (MCSearch == 1)
            {
                if(car.isMaintenance_certificate() == false )
                {
                    Object row[] = new Object[5];
                    row[0] = car;
                    row[1] = car.getModel_num();
                    row[2] = car.getMin_seats();
                    row[3] = car.getMax_seats();
                    row[4] = car.getAvailble_city();
                    dtm.addRow(row);
                }
            }
        }
    }//GEN-LAST:event_btnMCSearchActionPerformed

    private void MCComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MCComboBoxActionPerformed

    private void btnManuYearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManuYearSearchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)viewTable.getModel();
        dtm.setRowCount(0);
        int Year = Integer.parseInt(ManuYearTextField.getText());
        for ( Car car : carInformationList.getCarInformationList())
        {
            if(car.getManufactured_year()== Year){
                Object row[] = new Object[5];
                row[0] = car;
                row[1] = car.getModel_num();
                row[2] = car.getMin_seats();
                row[3] = car.getMax_seats();
                row[4] = car.getAvailble_city();
                dtm.addRow(row);

            }
        }
    }//GEN-LAST:event_btnManuYearSearchActionPerformed

    private void btnSearchBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBrandActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)viewTable.getModel();
        dtm.setRowCount(0);
        String brand = BrandTextField.getText();
        for ( Car car : carInformationList.getCarInformationList())
        {
            if(car.getBrand().equals(brand)){
                Object row[] = new Object[5];
                row[0] = car;
                row[1] = car.getModel_num();
                row[2] = car.getMin_seats();
                row[3] = car.getMax_seats();
                row[4] = car.getAvailble_city();
                dtm.addRow(row);
            }
        }
    }//GEN-LAST:event_btnSearchBrandActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)viewTable.getModel();
        dtm.setRowCount(0);

        for ( Car car : carInformationList.getCarInformationList())
        {
            Object row[] = new Object[5];
            row[0] = car;
            row[1] = car.getModel_num();
            row[2] = car.getMin_seats();
            row[3] = car.getMax_seats();
            row[4] = car.getAvailble_city();
            dtm.addRow(row);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here

        int selectedrow = viewTable.getSelectedRow();

        if (selectedrow >= 0)
        {
            Car car = (Car) viewTable.getValueAt(selectedrow, 0);
            ViewDetailsJPanel panel = new ViewDetailsJPanel(UserProcessContainer,carInformationList,car);
            UserProcessContainer.add("CreateJPanel",panel);
            CardLayout layout = (CardLayout)UserProcessContainer.getLayout();
            layout.next(UserProcessContainer);
        }
        else
        JOptionPane.showMessageDialog(null, "Please select row");
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedrow = viewTable.getSelectedRow();
        if (selectedrow >= 0)
        {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the account?", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION)
            {
                Car car = (Car) viewTable.getValueAt(selectedrow, 0);
                carInformationList.deleteCar(car);
                JOptionPane.showMessageDialog(null, "Deleted successfully");
                populateTable();
            }
            
        }
        else 
            JOptionPane.showMessageDialog(null, "Please select row");
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        txtFleetTime.setText(carInformationList.getLastupdated()+ "");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)viewTable.getModel();
        dtm.setRowCount(0);
        
        for ( Car car : carInformationList.getCarInformationList())
        {
            Object row[] = new Object[5];
            row[0] = car;
            row[1] = car.getModel_num();
            row[2] = car.getMin_seats();
            row[3] = car.getMax_seats();
            row[4] = car.getAvailble_city();
            dtm.addRow(row);
    }
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BrandTextField;
    private javax.swing.JTextField CityTextField;
    private javax.swing.JComboBox<String> MCComboBox;
    private javax.swing.JTextField ManuYearTextField;
    private javax.swing.JComboBox<String> MaxComboBox;
    private javax.swing.JComboBox<String> MinComboBox;
    private javax.swing.JTextField ModelNumberTextField;
    private javax.swing.JTextField SerialNumberTextField;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnFirstCarSearch;
    private javax.swing.JButton btnMCSearch;
    private javax.swing.JButton btnManuYearSearch;
    private javax.swing.JButton btnSearchAvail;
    private javax.swing.JButton btnSearchBrand;
    private javax.swing.JButton btnSearchCity;
    private javax.swing.JButton btnSearchModelNumber;
    private javax.swing.JButton btnSearchSeats;
    private javax.swing.JButton btnSearchSerialNumber;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JPanel citypanel;
    private javax.swing.JTabbedPane citytab;
    private javax.swing.JTextField countRowNATextField;
    private javax.swing.JTextField countrowTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFleetTime;
    private javax.swing.JTable viewTable;
    // End of variables declaration//GEN-END:variables
}
